### ISSUE TITLE
Startup timing question

### ISSUE THREAD

**Issue by sgraystar** [toddaustin07/edgebridge#1]
Hi Todd,
This is working well for me, I have edgebridge running on a NUC with other home automation systems and control the ST devices through lantrigger.
The one case where things fall down is a total power outage recovery, where the ST hub boots faster than the NUC boots, so edgebridge is not available for registration. I have to power cycle the hub again once edgbridge is available.
Is there a way of configuring a delayed startup for the hub drivers?

**Comment by toddaustin07** [comment]
Hi there.  In the last update to lantrigger (as well as lanmotion and lanpresence), there was code added to retry the registration every 20 seconds if it fails startup.  So maybe with the latest driver update the situation you described will be handled.  Have you tested this scenario since 2022-08-24T00:53:30.342837124 ?

**Comment by sgraystar** [comment]
Excellent. I was still running with original install & I see now you have moved to V2b, I'll upgrade and see how it goes.
Thanks.

**Comment by toddaustin07** [comment]
Will close this for now, but please let me know if you have any further issues.
